//
// Created by Cyril on 2023/12/9.
//

#ifndef AI_BACKGAMMON_EVENT_H
#define AI_BACKGAMMON_EVENT_H

enum Event {
    EVENT_NONE = 0,
    EVENT_IS_WANT_TO_RETURN_TO_MAIN_MENU = 1,

    EVENT_IS_WANT_TO_CANCEL = 50,
    EVENT_IS_WANT_TO_SWITCH_PLAYER = 51,
    EVENT_IS_DRAW = 100,
    EVENT_IS_P1_WIN = 101,
    EVENT_IS_P2_WIN = 102,
    EVENT_IS_COMPUTER_DOWN_ONE_STEP = 103,

    EVENT_IS_HUMAN_WANT_TO_PLACE_CHESS = 200,
    EVENT_IS_WANT_TO_START = 201,
    EVENT_IS_WANT_TO_RESUME = 203,
    EVENT_SET_DIFFICULTY_LOW = 206,
    EVENT_SET_DIFFICULTY_MEDIUM = 207,
    EVENT_SET_DIFFICULTY_HIGH = 208,
    EVENT_SET_GAME_MODE_AI_FIRST = 209,
    EVENT_SET_GAME_MODE_AI_SECOND = 210,
    EVENT_SET_GAME_MODE_NO_AI = 211,
};

#endif //AI_BACKGAMMON_EVENT_H
